# Generated by Django 4.1.7 on 2023-12-28 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='other_disease',
        ),
        migrations.AddField(
            model_name='patient',
            name='other_diseases',
            field=models.ManyToManyField(blank=True, related_name='other_diseases', to='patient.disease'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.disease'),
        ),
    ]
