# Generated by Django 4.1.7 on 2023-12-28 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
    ]
