# Generated by Django 4.1.7 on 2023-12-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_patient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
