# Generated by Django 4.1.7 on 2023-12-31 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_patient_img_1_alter_patient_img_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.city'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.disease'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='regiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.regiment'),
        ),
    ]
