# Generated by Django 4.1.7 on 2024-01-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_period_alter_day_name_alter_patient_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiment',
            name='period',
            field=models.CharField(choices=[('MORNING', 'MORNING'), ('EVENING', 'EVENING')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
