# Generated by Django 4.1.7 on 2024-01-01 13:52

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_regiment_period_delete_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=11, max_length=11, prefix='', primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='rest',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='surgery',
            field=models.BooleanField(default=False),
        ),
    ]
