# Generated by Django 4.1.7 on 2024-01-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_price_patient_rest_patient_surgery'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.price'),
        ),
    ]
