# Generated by Django 4.1.7 on 2024-01-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_patient_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_operation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
