# Generated by Django 4.1.7 on 2024-02-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_alter_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
