# Generated by Django 4.1.7 on 2024-01-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_customer_remove_order_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='amount',
        ),
    ]
