# Generated by Django 4.1.4 on 2023-04-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='description_EN',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='name_EN',
        ),
    ]
