# Generated by Django 4.1.4 on 2023-04-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_description_service_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_AR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_AR',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
