# Generated by Django 4.1.4 on 2023-04-01 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_description_fr_service_name_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='name',
        ),
    ]
