# Generated by Django 4.1.4 on 2023-04-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_subservice_description_remove_subservice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='description_EN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='name_EN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
