# Generated by Django 4.1.4 on 2023-04-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_subservice_description_en_subservice_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='description_AR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='name_AR',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
