# Generated by Django 4.1.4 on 2023-04-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_subservice_description_ar_subservice_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='description_FR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='name_FR',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
