# Generated by Django 4.1.4 on 2023-04-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_subservice_description_fr_subservice_name_fr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='subservice',
            old_name='id',
            new_name='uuid',
        ),
    ]
