# Generated by Django 4.1.7 on 2023-04-02 00:18

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_rename_id_service_uuid_rename_id_subservice_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='uuid',
        ),
        migrations.AddField(
            model_name='service',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='subservice',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
