# Generated by Django 4.1.7 on 2023-04-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_service_created_at_alter_service_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='updated_at',
        ),
    ]
