# Generated by Django 4.1.7 on 2023-04-02 00:41

from django.db import migrations
import shortuuidfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_remove_service_created_at_remove_service_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=uuid.uuid4, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=uuid.uuid4, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
