# Generated by Django 4.1.7 on 2023-04-02 09:24

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_alter_service_id_alter_subservice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=11, max_length=11, prefix='', primary_key=True, serialize=False),
        ),
    ]
