# Generated by Django 4.1.7 on 2023-04-11 20:08

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_alter_subservice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=11, max_length=11, prefix='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=11, max_length=11, prefix='', primary_key=True, serialize=False),
        ),
    ]
