# Generated by Django 4.1.7 on 2023-05-04 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_alter_service_image_alter_subservice_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='image_light',
        ),
        migrations.RenameField(
            model_name='subservice',
            old_name='img',
            new_name='image_light',
        ),
    ]
