# Generated by Django 4.1.7 on 2023-09-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_service_image_dark_subservice_image_dark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_dark',
            field=models.FileField(blank=True, default='images/subservice/default.svg', null=True, upload_to='images/service/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_light',
            field=models.FileField(blank=True, default='images/subservice/default.svg', null=True, upload_to='images/service/'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='image_dark',
            field=models.FileField(blank=True, default='images/subservice/default.svg', null=True, upload_to='images/subservice/'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='image_light',
            field=models.FileField(blank=True, default='images/subservice/default.svg', null=True, upload_to='images/subservice/'),
        ),
    ]
