# Generated by Django 4.1.4 on 2023-10-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_alter_service_image_dark_alter_service_image_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_dark',
            field=models.FileField(blank=True, default='images/subservice/default.svg', null=True, upload_to='images/service/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_light',
            field=models.FileField(blank=True, default='images/subservice/default.svg', null=True, upload_to='images/service/'),
        ),
    ]
