# Generated by Django 4.2.6 on 2023-11-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_alter_service_image_dark_alter_service_image_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
